// When travelling, open the Converter and Chart on the local currency -> EUR.
// The phone's time zone follows you abroad, so no location permission is needed.
// In Turkey, the eurozone or an unknown zone the page keeps its TRY -> EUR default.
(function () {
  var TARGET = 'EUR';

  var ZONES_BY_CURRENCY = {
    AED: 'Asia/Dubai',
    AFN: 'Asia/Kabul',
    ALL: 'Europe/Tirane',
    AMD: 'Asia/Yerevan',
    ANG: 'America/Curacao America/Lower_Princes',
    AOA: 'Africa/Luanda',
    ARS: 'America/Argentina/Buenos_Aires America/Argentina/Catamarca America/Argentina/ComodRivadavia America/Argentina/Cordoba America/Argentina/Jujuy America/Argentina/La_Rioja America/Argentina/Mendoza America/Argentina/Rio_Gallegos America/Argentina/Salta America/Argentina/San_Juan America/Argentina/San_Luis America/Argentina/Tucuman America/Argentina/Ushuaia America/Buenos_Aires America/Catamarca America/Cordoba America/Jujuy America/Mendoza America/Rosario',
    AUD: 'Antarctica/Macquarie Australia/ACT Australia/Adelaide Australia/Brisbane Australia/Broken_Hill Australia/Canberra Australia/Currie Australia/Darwin Australia/Eucla Australia/Hobart Australia/LHI Australia/Lindeman Australia/Lord_Howe Australia/Melbourne Australia/NSW Australia/North Australia/Perth Australia/Queensland Australia/South Australia/Sydney Australia/Tasmania Australia/Victoria Australia/West Australia/Yancowinna Indian/Christmas Indian/Cocos Pacific/Enderbury Pacific/Funafuti Pacific/Kanton Pacific/Kiritimati Pacific/Nauru Pacific/Norfolk Pacific/Tarawa',
    AWG: 'America/Aruba',
    AZN: 'Asia/Baku',
    BAM: 'Europe/Sarajevo',
    BBD: 'America/Barbados',
    BDT: 'Asia/Dacca Asia/Dhaka',
    BHD: 'Asia/Bahrain',
    BIF: 'Africa/Bujumbura',
    BMD: 'Atlantic/Bermuda',
    BND: 'Asia/Brunei',
    BOB: 'America/La_Paz',
    BRL: 'America/Araguaina America/Bahia America/Belem America/Boa_Vista America/Campo_Grande America/Cuiaba America/Eirunepe America/Fortaleza America/Maceio America/Manaus America/Noronha America/Porto_Acre America/Porto_Velho America/Recife America/Rio_Branco America/Santarem America/Sao_Paulo Brazil/Acre Brazil/DeNoronha Brazil/East Brazil/West',
    BSD: 'America/Nassau',
    BTN: 'Asia/Thimbu Asia/Thimphu',
    BWP: 'Africa/Gaborone',
    BYN: 'Europe/Minsk',
    BZD: 'America/Belize',
    CAD: 'America/Atikokan America/Blanc-Sablon America/Cambridge_Bay America/Creston America/Dawson America/Dawson_Creek America/Edmonton America/Fort_Nelson America/Glace_Bay America/Goose_Bay America/Halifax America/Inuvik America/Iqaluit America/Moncton America/Pangnirtung America/Rainy_River America/Rankin_Inlet America/Regina America/Resolute America/St_Johns America/Swift_Current America/Toronto America/Vancouver America/Whitehorse America/Winnipeg America/Yellowknife Canada/Atlantic Canada/Central Canada/Mountain Canada/Newfoundland Canada/Pacific Canada/Saskatchewan Canada/Yukon',
    CDF: 'Africa/Kinshasa Africa/Lubumbashi',
    CHF: 'Europe/Vaduz Europe/Zurich',
    CLP: 'America/Punta_Arenas America/Santiago Chile/Continental Chile/EasterIsland Pacific/Easter',
    CNY: 'Asia/Chongqing Asia/Chungking Asia/Harbin Asia/Kashgar Asia/Shanghai Asia/Urumqi PRC',
    COP: 'America/Bogota',
    CRC: 'America/Costa_Rica',
    CUP: 'America/Havana Cuba',
    CVE: 'Atlantic/Cape_Verde',
    CZK: 'Europe/Prague',
    DJF: 'Africa/Djibouti',
    DKK: 'America/Danmarkshavn America/Godthab America/Nuuk America/Scoresbysund America/Thule Atlantic/Faeroe Atlantic/Faroe Europe/Copenhagen',
    DOP: 'America/Santo_Domingo',
    DZD: 'Africa/Algiers',
    EGP: 'Africa/Cairo Egypt',
    ERN: 'Africa/Asmara',
    ETB: 'Africa/Addis_Ababa',
    FJD: 'Pacific/Fiji',
    FKP: 'Atlantic/Stanley',
    GBP: 'Atlantic/South_Georgia Europe/Belfast Europe/Guernsey Europe/Isle_of_Man Europe/Jersey Europe/London GB',
    GEL: 'Asia/Tbilisi',
    GHS: 'Africa/Accra',
    GIP: 'Europe/Gibraltar',
    GMD: 'Africa/Banjul',
    GNF: 'Africa/Conakry',
    GTQ: 'America/Guatemala',
    GYD: 'America/Guyana',
    HKD: 'Asia/Hong_Kong Hongkong',
    HNL: 'America/Tegucigalpa',
    HTG: 'America/Port-au-Prince',
    HUF: 'Europe/Budapest',
    IDR: 'Asia/Jakarta Asia/Jayapura Asia/Makassar Asia/Pontianak Asia/Ujung_Pandang',
    ILS: 'Asia/Gaza Asia/Hebron Asia/Jerusalem Asia/Tel_Aviv Israel',
    INR: 'Asia/Calcutta Asia/Kolkata',
    IQD: 'Asia/Baghdad',
    IRR: 'Asia/Tehran Iran',
    ISK: 'Atlantic/Reykjavik',
    JMD: 'America/Jamaica Jamaica',
    JOD: 'Asia/Amman',
    JPY: 'Asia/Tokyo Japan',
    KES: 'Africa/Nairobi',
    KGS: 'Asia/Bishkek',
    KHR: 'Asia/Phnom_Penh',
    KMF: 'Indian/Comoro',
    KPW: 'Asia/Pyongyang',
    KRW: 'Asia/Seoul ROK',
    KWD: 'Asia/Kuwait',
    KYD: 'America/Cayman',
    KZT: 'Asia/Almaty Asia/Aqtau Asia/Aqtobe Asia/Atyrau Asia/Oral Asia/Qostanay Asia/Qyzylorda',
    LAK: 'Asia/Vientiane',
    LBP: 'Asia/Beirut',
    LKR: 'Asia/Colombo',
    LRD: 'Africa/Monrovia',
    LSL: 'Africa/Maseru',
    LYD: 'Africa/Tripoli Libya',
    MAD: 'Africa/Casablanca Africa/El_Aaiun',
    MDL: 'Europe/Chisinau Europe/Tiraspol',
    MGA: 'Indian/Antananarivo',
    MKD: 'Europe/Skopje',
    MMK: 'Asia/Yangon',
    MNT: 'Asia/Choibalsan Asia/Hovd Asia/Ulaanbaatar Asia/Ulan_Bator',
    MOP: 'Asia/Macao Asia/Macau',
    MRU: 'Africa/Nouakchott',
    MUR: 'Indian/Mauritius',
    MVR: 'Indian/Maldives',
    MWK: 'Africa/Blantyre',
    MXN: 'America/Bahia_Banderas America/Cancun America/Chihuahua America/Ciudad_Juarez America/Ensenada America/Hermosillo America/Matamoros America/Mazatlan America/Merida America/Mexico_City America/Monterrey America/Ojinaga America/Santa_Isabel America/Tijuana Mexico/BajaNorte Mexico/BajaSur Mexico/General',
    MYR: 'Asia/Kuala_Lumpur Asia/Kuching',
    MZN: 'Africa/Maputo',
    NAD: 'Africa/Windhoek',
    NGN: 'Africa/Lagos',
    NIO: 'America/Managua',
    NOK: 'Arctic/Longyearbyen Europe/Oslo',
    NPR: 'Asia/Kathmandu Asia/Katmandu',
    NZD: 'Pacific/Auckland Pacific/Chatham Pacific/Fakaofo Pacific/Niue Pacific/Pitcairn Pacific/Rarotonga',
    OMR: 'Asia/Muscat',
    PAB: 'America/Panama',
    PEN: 'America/Lima',
    PGK: 'Pacific/Bougainville Pacific/Port_Moresby',
    PHP: 'Asia/Manila',
    PKR: 'Asia/Karachi',
    PLN: 'Europe/Warsaw Poland',
    PYG: 'America/Asuncion',
    QAR: 'Asia/Qatar',
    RON: 'Europe/Bucharest',
    RSD: 'Europe/Belgrade',
    RUB: 'Asia/Anadyr Asia/Barnaul Asia/Chita Asia/Irkutsk Asia/Kamchatka Asia/Khandyga Asia/Krasnoyarsk Asia/Magadan Asia/Novokuznetsk Asia/Novosibirsk Asia/Omsk Asia/Sakhalin Asia/Srednekolymsk Asia/Tomsk Asia/Ust-Nera Asia/Vladivostok Asia/Yakutsk Asia/Yekaterinburg Europe/Astrakhan Europe/Kaliningrad Europe/Kirov Europe/Moscow Europe/Samara Europe/Saratov Europe/Ulyanovsk Europe/Volgograd',
    RWF: 'Africa/Kigali',
    SAR: 'Asia/Riyadh',
    SBD: 'Pacific/Guadalcanal',
    SCR: 'Indian/Mahe',
    SDG: 'Africa/Khartoum',
    SEK: 'Europe/Stockholm',
    SGD: 'Asia/Singapore',
    SHP: 'Atlantic/St_Helena',
    SLE: 'Africa/Freetown',
    SOS: 'Africa/Mogadishu',
    SRD: 'America/Paramaribo',
    STN: 'Africa/Sao_Tome',
    SYP: 'Asia/Damascus',
    SZL: 'Africa/Mbabane',
    THB: 'Asia/Bangkok',
    TJS: 'Asia/Dushanbe',
    TMT: 'Asia/Ashgabat Asia/Ashkhabad',
    TND: 'Africa/Tunis',
    TOP: 'Pacific/Tongatapu',
    TTD: 'America/Port_of_Spain',
    TWD: 'Asia/Taipei ROC',
    TZS: 'Africa/Dar_es_Salaam',
    UAH: 'Europe/Kiev Europe/Kyiv Europe/Simferopol Europe/Uzhgorod Europe/Zaporozhye',
    UGX: 'Africa/Kampala',
    USD: 'America/Adak America/Anchorage America/Atka America/Boise America/Chicago America/Denver America/Detroit America/El_Salvador America/Fort_Wayne America/Grand_Turk America/Guayaquil America/Indiana/Indianapolis America/Indiana/Knox America/Indiana/Marengo America/Indiana/Petersburg America/Indiana/Tell_City America/Indiana/Vevay America/Indiana/Vincennes America/Indiana/Winamac America/Indianapolis America/Juneau America/Kentucky/Louisville America/Kentucky/Monticello America/Knox_IN America/Kralendijk America/Los_Angeles America/Louisville America/Menominee America/Metlakatla America/New_York America/Nome America/North_Dakota/Beulah America/North_Dakota/Center America/North_Dakota/New_Salem America/Phoenix America/Puerto_Rico America/Shiprock America/Sitka America/St_Thomas America/Tortola America/Yakutat Asia/Dili Indian/Chagos Pacific/Chuuk Pacific/Galapagos Pacific/Guam Pacific/Honolulu Pacific/Johnston Pacific/Kosrae Pacific/Kwajalein Pacific/Majuro Pacific/Midway Pacific/Pago_Pago Pacific/Palau Pacific/Pohnpei Pacific/Saipan Pacific/Samoa Pacific/Wake US/Alaska US/Aleutian US/Central US/East-Indiana US/Eastern US/Hawaii US/Indiana-Starke US/Michigan US/Mountain US/Pacific US/Samoa',
    UYU: 'America/Montevideo',
    UZS: 'Asia/Samarkand Asia/Tashkent',
    VES: 'America/Caracas',
    VND: 'Asia/Ho_Chi_Minh Asia/Saigon',
    VUV: 'Pacific/Efate',
    WST: 'Pacific/Apia',
    XAF: 'Africa/Bangui Africa/Brazzaville Africa/Douala Africa/Libreville Africa/Malabo Africa/Ndjamena',
    XCD: 'America/Anguilla America/Antigua America/Dominica America/Grenada America/Montserrat America/St_Kitts America/St_Lucia America/St_Vincent',
    XOF: 'Africa/Abidjan Africa/Bamako Africa/Bissau Africa/Dakar Africa/Lome Africa/Niamey Africa/Ouagadougou Africa/Porto-Novo',
    XPF: 'Pacific/Gambier Pacific/Marquesas Pacific/Noumea Pacific/Tahiti Pacific/Wallis',
    YER: 'Asia/Aden',
    ZAR: 'Africa/Johannesburg',
    ZMW: 'Africa/Lusaka',
    ZWG: 'Africa/Harare'
  };

  var zone;
  try {
    zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  } catch (error) {
    return;
  }

  var local = null;
  Object.keys(ZONES_BY_CURRENCY).some(function (currency) {
    if ((' ' + ZONES_BY_CURRENCY[currency] + ' ').indexOf(' ' + zone + ' ') === -1) return false;
    local = currency;
    return true;
  });
  if (!local) return;

  ['.widget-view--converter iframe', '.widget-view--chart iframe'].forEach(function (selector) {
    var frame = document.querySelector(selector);
    if (!frame) return;
    var url = new URL(frame.src);
    url.searchParams.set('sourceCurrency', local);
    url.searchParams.set('targetCurrency', TARGET);
    frame.src = url.toString();
  });
})();
